version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch-latest
    environment:
      - cluster.name=hackathon
      - bootstrap.memory_lock=true
      - node.name=stretch_armstrong
      - node.ml=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=${SECURITY_ENABLED}
      - xpack.monitoring.enabled=${MONITORING_ENABLED}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - esnet    
  ki01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana-latest
    hostname: kibana
    ports: ['5601:5601']
    networks: ['esnet']
    depends_on: ['es01']
    restart: on-failure
    environment:
      - XPACK_MONITORING_ENABLED=${MONITORING_ENABLED}
      - ELASTICSEARCH_HOSTS=http://es01:9200

volumes:
  es-data:

networks:
  esnet:
